spring:
  application:
    name: push-notification
  cloud:
    config:
      uri: http://localhost:8888
    stream:
      default-binder: local_kafka
      bindings:
        input:
          destination: spring-boot-chat
          group: comments-chat
          content-type: application/json
        newComments:
          destination: spring-boot-chat
          group: comments-chat
          content-type: application/json
        clientToBroker:
          destination: chat-user-messages
          group: app-chatMessages
        brokerToClient:
          destination: chat-user-messages
          group: topic-chatMessages
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                #                host: baboon.rmq.cloudamqp.com
                #                port: 5672
                #                username: dhkruxqt
                #                password: oUwLJACFqSKb1Y8ylzjJoBwHmOfYypkA
                #                virtual-host: dhkruxqt
                host: localhost
                port: 5673
                username: admin
                password: parola86
                virtual-host: /
        local_kafka:
          type: kafka
          environment:
            spring:
              kafka:
                host: localhost
                port: 9092

server:
  port: ${PORT:9001}

mqtt:
  broker_url: tcp://localhost:1883
  client: iotClient
  topic: machine

redis:
  host: localhost
  port: 6380

websocket:
  replay_messages: 25
  inbound_url: /app/chatMessage.new
  outbound_url: /topic/chatMessage.new
